curl 'https://machinelearning.temanumroh.com/api/classes/session-users/students/b9c94423-e0e2-4860-b94f-4d24843b1b1f/localprojects' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Accept-Language: en-US,en;q=0.9' \
  -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImI5Yzk0NDIzLWUwZTItNDg2MC1iOTRmLTRkMjQ4NDNiMWIxZiIsInRva2VuIjoiZWU0MDkyZWItZjJhZi00ZGE5LWFmZGQtMThiNTNiYjE2YWQ2Iiwic2Vzc2lvbkV4cGlyeSI6IjIwMjQtMDItMjRUMDQ6MDk6NTguMDAwWiIsImlhdCI6MTcwODczMzM5OX0.Rv38JokxrOt5QudtAcMeyf_IquNFFPT4BeeQlnheh_c' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: application/json;charset=UTF-8' \
  -H 'Origin: https://machinelearning.temanumroh.com' \
  -H 'Pragma: no-cache' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36' \
  -H 'sec-ch-ua: "Not A(Brand";v="99", "Google Chrome";v="121", "Chromium";v="121"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Linux"' \
  --data-raw '{"name":"asas","type":"text","storage":"local","language":"en","isCrowdSourced":false,"userid":"b9c94423-e0e2-4860-b94f-4d24843b1b1f","classid":"session-users","labels":["asas","sd"],"id":4}' \
  --compressed